pub fn generated_graph_module(plan: &boon_compiler::CompilePlan) -> String {
    let graph = &plan.graph;
    let dd_graph_ir = &plan.dd_graph_ir;
    let mut code = String::new();
    code.push_str("// @generated by boon_codegen_rust\n");
    code.push_str("// Constructs a static Timely/Differential graph; hosts only inject sources and drain probes.\n");
    code.push_str("use differential_dataflow::input::InputSession;\n");
    code.push_str("use boon_dd::{BoonTime, Diff, EncodedTime, GeneratedSourceEvent, GeneratedSourceEventPayload, MonitorRecord, NodeId, OwnerKey, RenderCommand, SmokeOutput, SourceAction, SourceFamilyId, SourceId};\n");
    code.push_str("use std::sync::{Arc, Mutex};\n");
    code.push_str("use timely::dataflow::operators::probe::Handle as ProbeHandle;\n\n");
    code.push_str("pub struct GeneratedSourceInputs {\n");
    code.push_str("    input: InputSession<EncodedTime, (u64, GeneratedSourceEvent), Diff>,\n");
    code.push_str("    output: Arc<Mutex<Vec<SmokeOutput>>>,\n");
    code.push_str("    next_sequence: u64,\n");
    code.push_str("}\n\n");
    code.push_str("impl GeneratedSourceInputs {\n");
    code.push_str(
        "    pub fn submit_event(&mut self, event: GeneratedSourceEvent, epoch: u64) {\n",
    );
    code.push_str("        self.input.advance_to(BoonTime { epoch, phase: 0 }.encode());\n");
    code.push_str("        let sequence = self.next_sequence;\n");
    code.push_str("        self.next_sequence += 1;\n");
    code.push_str("        self.input.insert((sequence, event));\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn submit_action(&mut self, action: &SourceAction, epoch: u64) {\n");
    code.push_str("        let payload = boon_dd::source_action_payload(action);\n");
    code.push_str("        let event = match (&action.owner, action.generation) {\n");
    code.push_str("            (Some(owner), generation) => GeneratedSourceEvent::Dynamic {\n");
    code.push_str("                family_id: SourceFamilyId(action.source.clone()),\n");
    code.push_str("                owner_key: owner.clone(),\n");
    code.push_str("                generation: generation.unwrap_or_default(),\n");
    code.push_str("                payload,\n");
    code.push_str("            },\n");
    code.push_str("            (None, _) => GeneratedSourceEvent::Static {\n");
    code.push_str("                source_id: SourceId(source_id_for_path(&action.source)),\n");
    code.push_str("                payload,\n");
    code.push_str("            },\n");
    code.push_str("        };\n");
    code.push_str("        self.submit_event(event, epoch);\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn submit_host_tick(&mut self, epoch: u64) {\n");
    code.push_str("        self.submit_event(GeneratedSourceEvent::Static {\n");
    code.push_str("            source_id: SourceId(\"__host_tick\".to_owned()),\n");
    code.push_str("            payload: GeneratedSourceEventPayload::EmptyRecord,\n");
    code.push_str("        }, epoch);\n");
    code.push_str("    }\n\n");
    code.push_str(
        "    pub fn submit_persisted_text(&mut self, value: impl Into<String>, epoch: u64) {\n",
    );
    code.push_str("        self.submit_event(GeneratedSourceEvent::Static {\n");
    code.push_str("            source_id: SourceId(\"__persisted_text\".to_owned()),\n");
    code.push_str("            payload: GeneratedSourceEventPayload::Text(value.into()),\n");
    code.push_str("        }, epoch);\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn close_epoch(&mut self, epoch: u64) {\n");
    code.push_str("        self.input.advance_to(completion_time(epoch) + 1);\n");
    code.push_str("        self.input.flush();\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn outputs(&self) -> Vec<SmokeOutput> {\n");
    code.push_str(
        "        self.output.lock().expect(\"generated output lock poisoned\").clone()\n",
    );
    code.push_str("    }\n");
    code.push_str("}\n\n");
    code.push_str("pub struct GeneratedGraphHandles {\n");
    code.push_str("    pub sources: GeneratedSourceInputs,\n");
    code.push_str("    pub probe: ProbeHandle<EncodedTime>,\n");
    code.push_str("}\n\n");
    code.push_str("impl GeneratedGraphHandles {\n");
    code.push_str("    pub fn submit_event_and_drain(\n");
    code.push_str("        &mut self,\n");
    code.push_str("        worker: &mut timely::worker::Worker,\n");
    code.push_str("        event: GeneratedSourceEvent,\n");
    code.push_str("        epoch: u64,\n");
    code.push_str("        max_steps: usize,\n");
    code.push_str("    ) -> Result<Vec<SmokeOutput>, String> {\n");
    code.push_str("        self.sources.submit_event(event, epoch);\n");
    code.push_str("        self.sources.close_epoch(epoch);\n");
    code.push_str("        let target = completion_time(epoch) + 1;\n");
    code.push_str("        let mut steps = 0_usize;\n");
    code.push_str("        while self.probe.less_than(&target) {\n");
    code.push_str("            if steps == max_steps {\n");
    code.push_str("                return Err(format!(\"generated graph probe stalled at {target} after {steps} steps\"));\n");
    code.push_str("            }\n");
    code.push_str("            worker.step();\n");
    code.push_str("            steps += 1;\n");
    code.push_str("        }\n");
    code.push_str("        Ok(self.sources.outputs())\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    code.push_str("pub fn graph_id() -> &'static str {\n");
    code.push_str(&format!("    {:?}\n", graph.graph_id));
    code.push_str("}\n\n");
    code.push_str(
        "pub fn build_dataflow_description() -> &'static [(&'static str, &'static str)] {\n",
    );
    code.push_str("    &[\n");
    for operator in &graph.operators {
        code.push_str(&format!(
            "        ({:?}, {:?}),\n",
            operator.node.0,
            format!("{:?}", operator.kind)
        ));
    }
    code.push_str("    ]\n");
    code.push_str("}\n\n");
    code.push_str("pub fn completion_time(epoch: u64) -> u64 {\n");
    code.push_str("    BoonTime { epoch, phase: 3 }.encode()\n");
    code.push_str("}\n\n");
    code.push_str("fn source_id_for_path(path: &str) -> String {\n");
    code.push_str("    match path {\n");
    for source in &graph.source_bindings {
        code.push_str(&format!(
            "        {:?} => {:?}.to_owned(),\n",
            source.path, source.source_id.0
        ));
    }
    code.push_str("        other => other.to_owned(),\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    code.push_str("pub fn build_dataflow(\n");
    code.push_str("    worker: &mut timely::worker::Worker,\n");
    code.push_str(") -> GeneratedGraphHandles {\n");
    code.push_str("    let mut input = InputSession::<EncodedTime, (u64, GeneratedSourceEvent), Diff>::new();\n");
    code.push_str("    let mut probe = ProbeHandle::new();\n");
    code.push_str("    let output = Arc::new(Mutex::new(Vec::<SmokeOutput>::new()));\n");
    code.push_str("    let output_in_graph = Arc::clone(&output);\n");
    code.push_str(&format!(
        "    let monitor_node = NodeId({:?}.to_owned());\n",
        graph.monitor_node.0
    ));
    code.push_str(&format!(
        "    let render_node = NodeId({:?}.to_owned());\n",
        graph.render_node.0
    ));
    code.push_str("    worker.dataflow::<EncodedTime, _, _>(|scope| {\n");
    code.push_str("        let events = input.to_collection(scope);\n");
    code.push_str(&render_collection_from_program(&dd_graph_ir.render_program));
    code.push_str("        rendered\n");
    code.push_str("            .inspect(move |(text, time, diff)| {\n");
    code.push_str("                if *diff > 0 {\n");
    code.push_str("                    output_in_graph.lock().expect(\"generated output lock poisoned\").push(SmokeOutput {\n");
    code.push_str("                        monitor: vec![MonitorRecord::NodeValue {\n");
    code.push_str("                            epoch: BoonTime::decode(*time).epoch,\n");
    code.push_str("                            node: monitor_node.clone(),\n");
    code.push_str("                            owner: OwnerKey(\"Root\".to_owned()),\n");
    code.push_str("                            value_preview: text.clone(),\n");
    code.push_str("                        }],\n");
    code.push_str("                        render: vec![RenderCommand::PatchText {\n");
    code.push_str("                            node: render_node.clone(),\n");
    code.push_str("                            text: text.clone(),\n");
    code.push_str("                        }],\n");
    code.push_str("                    });\n");
    code.push_str("                }\n");
    code.push_str("            })\n");
    code.push_str("            .probe_with(&mut probe);\n");
    code.push_str("    });\n");
    code.push_str("    GeneratedGraphHandles {\n");
    code.push_str("        sources: GeneratedSourceInputs { input, output, next_sequence: 0 },\n");
    code.push_str("        probe,\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    code
}

fn render_collection_from_program(program: &boon_dd::DdRenderProgram) -> String {
    match &program.operation {
        boon_dd::DdRenderOperation::ConstantText(text) => format!(
            "        let rendered = events.map(|_| ()).count().filter(|(_key, count)| *count > 0).map(|_| {:?}.to_owned());\n",
            text
        ),
        boon_dd::DdRenderOperation::CountInputEvents { initial } => format!(
            "        let rendered = events.map(|_| ()).count().map(|(_key, count)| ({} + count as i64).to_string());\n",
            initial
        ),
        boon_dd::DdRenderOperation::LatestInputText => {
            "        let rendered = events.map(|(sequence, event)| ((), (sequence, boon_dd::generated_source_event_text(&event)))).reduce(|_, inputs, output| {\n            if let Some(((_sequence, value), _diff)) = inputs.iter().max_by_key(|((sequence, _), _)| *sequence) {\n                output.push((value.clone(), 1));\n            }\n        }).map(|(_key, value)| value);\n".to_owned()
        }
        boon_dd::DdRenderOperation::MatchTagText { tag, text } => format!(
            "        let rendered = events.filter(|(_sequence, event)| boon_dd::generated_source_event_text(event) == {:?}).map(|_| {:?}.to_owned());\n",
            tag, text
        ),
    }
}
