use std::collections::BTreeMap;

pub fn generated_graph_module(plan: &boon_compiler::CompilePlan) -> String {
    let graph = &plan.graph;
    let dd_graph_ir = &plan.dd_graph_ir;
    let mut code = String::new();
    code.push_str("// @generated by boon_codegen_rust\n");
    code.push_str("// Constructs a static Timely/Differential graph; hosts only inject sources and drain probes.\n");
    code.push_str("use differential_dataflow::input::InputSession;\n");
    code.push_str("use boon_dd::{BoonTime, Diff, EncodedTime, GeneratedSourceEvent, GeneratedSourceEventPayload, MonitorRecord, NodeId, OwnerKey, RenderCommand, SmokeOutput, SourceAction, SourceFamilyId, SourceId};\n");
    code.push_str("use std::sync::{Arc, Mutex};\n");
    code.push_str("use timely::dataflow::operators::probe::Handle as ProbeHandle;\n\n");
    code.push_str(
        "#[allow(dead_code)]\n#[derive(Clone, Debug)]\nenum GeneratedValue {\n    Empty,\n    Text(String),\n    Number(i64),\n    Tag(String),\n    List(Vec<GeneratedValue>),\n    Record(Vec<(String, GeneratedValue)>),\n}\n\n",
    );
    code.push_str(
        "#[allow(dead_code)]\nimpl GeneratedValue {\n    fn text(self) -> String {\n        match self {\n            GeneratedValue::Empty => String::new(),\n            GeneratedValue::Text(text) => text,\n            GeneratedValue::Number(number) => number.to_string(),\n            GeneratedValue::Tag(tag) => tag,\n            GeneratedValue::List(values) => values.into_iter().map(GeneratedValue::text).collect::<Vec<_>>().join(\",\"),\n            GeneratedValue::Record(_) => String::new(),\n        }\n    }\n\n    fn number(self) -> i64 {\n        match self {\n            GeneratedValue::Number(number) => number,\n            GeneratedValue::Text(text) => text.parse().unwrap_or(0),\n            _ => 0,\n        }\n    }\n\n    fn field(self, name: &str) -> GeneratedValue {\n        match self {\n            GeneratedValue::Record(fields) => fields.into_iter().find(|(field, _)| field == name).map(|(_, value)| value).unwrap_or(GeneratedValue::Empty),\n            _ => GeneratedValue::Empty,\n        }\n    }\n\n    fn truthy(self) -> bool {\n        match self {\n            GeneratedValue::Tag(tag) => tag == \"True\",\n            GeneratedValue::Text(text) => !text.is_empty(),\n            GeneratedValue::Number(number) => number != 0,\n            GeneratedValue::List(values) => !values.is_empty(),\n            GeneratedValue::Record(fields) => !fields.is_empty(),\n            GeneratedValue::Empty => false,\n        }\n    }\n}\n\n",
    );
    code.push_str("pub struct GeneratedSourceInputs {\n");
    code.push_str("    input: InputSession<EncodedTime, (u64, GeneratedSourceEvent), Diff>,\n");
    code.push_str("    output: Arc<Mutex<Vec<SmokeOutput>>>,\n");
    code.push_str("    next_sequence: u64,\n");
    code.push_str("}\n\n");
    code.push_str("impl GeneratedSourceInputs {\n");
    code.push_str(
        "    pub fn submit_event(&mut self, event: GeneratedSourceEvent, epoch: u64) {\n",
    );
    code.push_str("        self.input.advance_to(BoonTime { epoch, phase: 0 }.encode());\n");
    code.push_str("        let sequence = self.next_sequence;\n");
    code.push_str("        self.next_sequence += 1;\n");
    code.push_str("        self.input.insert((sequence, event));\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn submit_action(&mut self, action: &SourceAction, epoch: u64) {\n");
    code.push_str("        let payload = boon_dd::source_action_payload(action);\n");
    code.push_str("        let event = match (&action.owner, action.generation) {\n");
    code.push_str("            (Some(owner), generation) => GeneratedSourceEvent::Dynamic {\n");
    code.push_str("                family_id: SourceFamilyId(action.source.clone()),\n");
    code.push_str("                owner_key: owner.clone(),\n");
    code.push_str("                generation: generation.unwrap_or_default(),\n");
    code.push_str("                payload,\n");
    code.push_str("            },\n");
    code.push_str("            (None, _) => GeneratedSourceEvent::Static {\n");
    code.push_str("                source_id: SourceId(source_id_for_path(&action.source)),\n");
    code.push_str("                payload,\n");
    code.push_str("            },\n");
    code.push_str("        };\n");
    code.push_str("        self.submit_event(event, epoch);\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn submit_host_tick(&mut self, epoch: u64) {\n");
    code.push_str("        self.submit_event(GeneratedSourceEvent::Static {\n");
    code.push_str("            source_id: SourceId(\"__host_tick\".to_owned()),\n");
    code.push_str("            payload: GeneratedSourceEventPayload::EmptyRecord,\n");
    code.push_str("        }, epoch);\n");
    code.push_str("    }\n\n");
    code.push_str(
        "    pub fn submit_persisted_text(&mut self, value: impl Into<String>, epoch: u64) {\n",
    );
    code.push_str("        self.submit_event(GeneratedSourceEvent::Static {\n");
    code.push_str("            source_id: SourceId(\"__persisted_text\".to_owned()),\n");
    code.push_str("            payload: GeneratedSourceEventPayload::Text(value.into()),\n");
    code.push_str("        }, epoch);\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn close_epoch(&mut self, epoch: u64) {\n");
    code.push_str("        self.input.advance_to(completion_time(epoch) + 1);\n");
    code.push_str("        self.input.flush();\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn outputs(&self) -> Vec<SmokeOutput> {\n");
    code.push_str(
        "        self.output.lock().expect(\"generated output lock poisoned\").clone()\n",
    );
    code.push_str("    }\n");
    code.push_str("}\n\n");
    code.push_str("pub struct GeneratedGraphHandles {\n");
    code.push_str("    pub sources: GeneratedSourceInputs,\n");
    code.push_str("    pub probe: ProbeHandle<EncodedTime>,\n");
    code.push_str("}\n\n");
    code.push_str("impl GeneratedGraphHandles {\n");
    code.push_str("    pub fn submit_event_and_drain(\n");
    code.push_str("        &mut self,\n");
    code.push_str("        worker: &mut timely::worker::Worker,\n");
    code.push_str("        event: GeneratedSourceEvent,\n");
    code.push_str("        epoch: u64,\n");
    code.push_str("        max_steps: usize,\n");
    code.push_str("    ) -> Result<Vec<SmokeOutput>, String> {\n");
    code.push_str("        self.sources.submit_event(event, epoch);\n");
    code.push_str("        self.sources.close_epoch(epoch);\n");
    code.push_str("        let target = completion_time(epoch) + 1;\n");
    code.push_str("        let mut steps = 0_usize;\n");
    code.push_str("        while self.probe.less_than(&target) {\n");
    code.push_str("            if steps == max_steps {\n");
    code.push_str("                return Err(format!(\"generated graph probe stalled at {target} after {steps} steps\"));\n");
    code.push_str("            }\n");
    code.push_str("            worker.step();\n");
    code.push_str("            steps += 1;\n");
    code.push_str("        }\n");
    code.push_str("        Ok(self.sources.outputs())\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    code.push_str("pub fn graph_id() -> &'static str {\n");
    code.push_str(&format!("    {:?}\n", graph.graph_id));
    code.push_str("}\n\n");
    code.push_str(
        "pub fn build_dataflow_description() -> &'static [(&'static str, &'static str)] {\n",
    );
    code.push_str("    &[\n");
    for operator in &graph.operators {
        code.push_str(&format!(
            "        ({:?}, {:?}),\n",
            operator.node.0,
            format!("{:?}", operator.kind)
        ));
    }
    code.push_str("    ]\n");
    code.push_str("}\n\n");
    code.push_str("pub fn completion_time(epoch: u64) -> u64 {\n");
    code.push_str("    BoonTime { epoch, phase: 3 }.encode()\n");
    code.push_str("}\n\n");
    code.push_str("fn source_id_for_path(path: &str) -> String {\n");
    code.push_str("    match path {\n");
    for source in &graph.source_bindings {
        code.push_str(&format!(
            "        {:?} => {:?}.to_owned(),\n",
            source.path, source.source_id.0
        ));
    }
    code.push_str("        other => other.to_owned(),\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    code.push_str("pub fn build_dataflow(\n");
    code.push_str("    worker: &mut timely::worker::Worker,\n");
    code.push_str(") -> GeneratedGraphHandles {\n");
    code.push_str("    let mut input = InputSession::<EncodedTime, (u64, GeneratedSourceEvent), Diff>::new();\n");
    code.push_str("    let mut probe = ProbeHandle::new();\n");
    code.push_str("    let output = Arc::new(Mutex::new(Vec::<SmokeOutput>::new()));\n");
    code.push_str("    let output_in_graph = Arc::clone(&output);\n");
    code.push_str(&format!(
        "    let monitor_node = NodeId({:?}.to_owned());\n",
        graph.monitor_node.0
    ));
    code.push_str(&format!(
        "    let render_node = NodeId({:?}.to_owned());\n",
        graph.render_node.0
    ));
    let effect_commands = effect_commands_from_protocol(&dd_graph_ir.output_protocol);
    code.push_str("    worker.dataflow::<EncodedTime, _, _>(|scope| {\n");
    code.push_str("        let events = input.to_collection(scope);\n");
    code.push_str(&render_collection_from_program(&dd_graph_ir.render_program));
    code.push_str("        rendered\n");
    code.push_str("            .inspect(move |(text, time, diff)| {\n");
    code.push_str("                if *diff > 0 {\n");
    code.push_str("                    output_in_graph.lock().expect(\"generated output lock poisoned\").push(SmokeOutput {\n");
    code.push_str("                        monitor: vec![MonitorRecord::NodeValue {\n");
    code.push_str("                            epoch: BoonTime::decode(*time).epoch,\n");
    code.push_str("                            node: monitor_node.clone(),\n");
    code.push_str("                            owner: OwnerKey(\"Root\".to_owned()),\n");
    code.push_str("                            value_preview: text.clone(),\n");
    code.push_str("                        }],\n");
    code.push_str("                        render: vec![RenderCommand::PatchText {\n");
    code.push_str("                            node: render_node.clone(),\n");
    code.push_str("                            text: text.clone(),\n");
    code.push_str("                        }],\n");
    code.push_str(&format!(
        "                        effects: {},\n",
        effect_commands
    ));
    code.push_str("                        persistence: Vec::new(),\n");
    code.push_str("                    });\n");
    code.push_str("                }\n");
    code.push_str("            })\n");
    code.push_str("            .probe_with(&mut probe);\n");
    code.push_str("    });\n");
    code.push_str("    GeneratedGraphHandles {\n");
    code.push_str("        sources: GeneratedSourceInputs { input, output, next_sequence: 0 },\n");
    code.push_str("        probe,\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    code
}

fn effect_commands_from_protocol(protocol: &boon_dd::DdOutputProtocol) -> String {
    let commands = protocol
        .sinks
        .iter()
        .filter_map(|sink| match sink {
            boon_dd::DdOutputSink::Effect { node, name, .. } => Some(format!(
                "boon_dd::EffectCommand::Requested {{ node: NodeId({:?}.to_owned()), name: {:?}.to_owned() }}",
                node.0, name
            )),
            _ => None,
        })
        .collect::<Vec<_>>();
    if commands.is_empty() {
        "Vec::new()".to_owned()
    } else {
        format!("vec![{}]", commands.join(", "))
    }
}

fn render_collection_from_program(program: &boon_dd::DdRenderProgram) -> String {
    match &program.operation {
        boon_dd::DdRenderOperation::Text { expr } => render_collection_from_expr(expr),
    }
}

fn render_collection_from_expr(expr: &boon_dd::DdRenderExpr) -> String {
    if let Some(initial) = count_sum_initial(expr) {
        return format!(
            "        let rendered = events.map(|_| ()).count().map(|(_key, count)| ({} + count as i64).to_string());\n",
            initial
        );
    }
    if let Some(value) = then_body_value(expr) {
        let value = value_expr_code(value, &BTreeMap::new());
        return format!(
            "        let rendered = events.map(|_| ({}).text());\n",
            value
        );
    }
    if has_latest(expr) {
        return "        let rendered = events.map(|(sequence, event)| ((), (sequence, boon_dd::generated_source_event_text(&event)))).reduce(|_, inputs, output| {\n            if let Some(((_sequence, value), _diff)) = inputs.iter().max_by_key(|((sequence, _), _)| *sequence) {\n                output.push((value.clone(), 1));\n            }\n        }).map(|(_key, value)| value);\n".to_owned();
    }
    if let Some((tag, value)) = first_match_arm(expr) {
        let value = value_expr_code(value, &BTreeMap::new());
        return format!(
            "        let rendered = events.filter(|(_sequence, event)| boon_dd::generated_source_event_text(event) == {:?}).map(|_| ({}).text());\n",
            tag, value
        );
    }
    let value = value_expr_code(expr, &BTreeMap::new());
    format!(
        "        let rendered = events.map(|_| ()).count().filter(|(_key, count)| *count > 0).map(|_| ({}).text());\n",
        value
    )
}

fn count_sum_initial(expr: &boon_dd::DdRenderExpr) -> Option<i64> {
    match expr {
        boon_dd::DdRenderExpr::Pipe { input, stage } if call_callee(stage, "Math/sum") => Some(0),
        boon_dd::DdRenderExpr::Pipe { input, stage }
            if matches!(stage.as_ref(), boon_dd::DdRenderExpr::Hold { .. }) =>
        {
            Some(number_literal(input).unwrap_or(0))
        }
        boon_dd::DdRenderExpr::Pipe { input, stage } => {
            count_sum_initial(stage).or_else(|| count_sum_initial(input))
        }
        _ => None,
    }
}

fn then_body_value(expr: &boon_dd::DdRenderExpr) -> Option<&boon_dd::DdRenderExpr> {
    match expr {
        boon_dd::DdRenderExpr::Then { body } => body.last(),
        boon_dd::DdRenderExpr::Pipe { stage, .. } => then_body_value(stage),
        _ => None,
    }
}

fn has_latest(expr: &boon_dd::DdRenderExpr) -> bool {
    walk_render_expr(expr, &mut |value| {
        matches!(value, boon_dd::DdRenderExpr::Latest(_))
    })
}

fn first_match_arm(expr: &boon_dd::DdRenderExpr) -> Option<(&str, &boon_dd::DdRenderExpr)> {
    match expr {
        boon_dd::DdRenderExpr::Match { arms, .. } => arms
            .iter()
            .find(|arm| arm.pattern != "__")
            .map(|arm| (arm.pattern.as_str(), &arm.value)),
        boon_dd::DdRenderExpr::Record(fields)
        | boon_dd::DdRenderExpr::Constructor { fields, .. } => fields
            .iter()
            .find_map(|field| first_match_arm(&field.value)),
        boon_dd::DdRenderExpr::List(values)
        | boon_dd::DdRenderExpr::Block(values)
        | boon_dd::DdRenderExpr::Latest(values)
        | boon_dd::DdRenderExpr::Then { body: values }
        | boon_dd::DdRenderExpr::Hold { body: values, .. } => {
            values.iter().find_map(first_match_arm)
        }
        boon_dd::DdRenderExpr::Call { args, .. } => args.iter().find_map(|arg| match arg {
            boon_dd::DdRenderArg::Positional(value) | boon_dd::DdRenderArg::Named { value, .. } => {
                first_match_arm(value)
            }
        }),
        boon_dd::DdRenderExpr::Pipe { input, stage }
        | boon_dd::DdRenderExpr::BinaryAdd {
            left: input,
            right: stage,
        } => first_match_arm(input).or_else(|| first_match_arm(stage)),
        boon_dd::DdRenderExpr::Missing
        | boon_dd::DdRenderExpr::Path(_)
        | boon_dd::DdRenderExpr::Number(_)
        | boon_dd::DdRenderExpr::Source
        | boon_dd::DdRenderExpr::Skip
        | boon_dd::DdRenderExpr::Tag(_)
        | boon_dd::DdRenderExpr::Text(_) => None,
    }
}

fn call_callee(expr: &boon_dd::DdRenderExpr, expected: &str) -> bool {
    matches!(expr, boon_dd::DdRenderExpr::Call { callee, .. } if callee == expected)
}

fn number_literal(expr: &boon_dd::DdRenderExpr) -> Option<i64> {
    match expr {
        boon_dd::DdRenderExpr::Number(number) => number.parse().ok(),
        _ => None,
    }
}

fn walk_render_expr<F>(expr: &boon_dd::DdRenderExpr, predicate: &mut F) -> bool
where
    F: FnMut(&boon_dd::DdRenderExpr) -> bool,
{
    if predicate(expr) {
        return true;
    }
    match expr {
        boon_dd::DdRenderExpr::Record(fields)
        | boon_dd::DdRenderExpr::Constructor { fields, .. } => fields
            .iter()
            .any(|field| walk_render_expr(&field.value, predicate)),
        boon_dd::DdRenderExpr::List(values)
        | boon_dd::DdRenderExpr::Block(values)
        | boon_dd::DdRenderExpr::Latest(values)
        | boon_dd::DdRenderExpr::Then { body: values }
        | boon_dd::DdRenderExpr::Hold { body: values, .. } => values
            .iter()
            .any(|value| walk_render_expr(value, predicate)),
        boon_dd::DdRenderExpr::Call { args, .. } => args.iter().any(|arg| match arg {
            boon_dd::DdRenderArg::Positional(value) | boon_dd::DdRenderArg::Named { value, .. } => {
                walk_render_expr(value, predicate)
            }
        }),
        boon_dd::DdRenderExpr::Pipe { input, stage }
        | boon_dd::DdRenderExpr::BinaryAdd {
            left: input,
            right: stage,
        } => walk_render_expr(input, predicate) || walk_render_expr(stage, predicate),
        boon_dd::DdRenderExpr::Match { arms, .. } => arms
            .iter()
            .any(|arm| walk_render_expr(&arm.value, predicate)),
        boon_dd::DdRenderExpr::Missing
        | boon_dd::DdRenderExpr::Path(_)
        | boon_dd::DdRenderExpr::Number(_)
        | boon_dd::DdRenderExpr::Source
        | boon_dd::DdRenderExpr::Skip
        | boon_dd::DdRenderExpr::Tag(_)
        | boon_dd::DdRenderExpr::Text(_) => false,
    }
}

fn value_expr_code(expr: &boon_dd::DdRenderExpr, env: &BTreeMap<String, String>) -> String {
    match expr {
        boon_dd::DdRenderExpr::Missing
        | boon_dd::DdRenderExpr::Source
        | boon_dd::DdRenderExpr::Skip => "GeneratedValue::Empty".to_owned(),
        boon_dd::DdRenderExpr::Path(path) => path_expr_code(path, env),
        boon_dd::DdRenderExpr::Number(number) => {
            format!(
                "GeneratedValue::Number({}.parse::<i64>().unwrap_or(0))",
                quote(number)
            )
        }
        boon_dd::DdRenderExpr::Tag(tag) => {
            format!("GeneratedValue::Tag({}.to_owned())", quote(tag))
        }
        boon_dd::DdRenderExpr::Text(text) => {
            format!("GeneratedValue::Text({}.to_owned())", quote(text))
        }
        boon_dd::DdRenderExpr::Record(fields)
        | boon_dd::DdRenderExpr::Constructor { fields, .. } => {
            let fields = fields
                .iter()
                .map(|field| {
                    format!(
                        "({}.to_owned(), {})",
                        quote(&field.name),
                        value_expr_code(&field.value, env)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("GeneratedValue::Record(vec![{}])", fields)
        }
        boon_dd::DdRenderExpr::List(values) => {
            let values = values
                .iter()
                .map(|value| value_expr_code(value, env))
                .collect::<Vec<_>>()
                .join(", ");
            format!("GeneratedValue::List(vec![{}])", values)
        }
        boon_dd::DdRenderExpr::Block(values)
        | boon_dd::DdRenderExpr::Latest(values)
        | boon_dd::DdRenderExpr::Then { body: values }
        | boon_dd::DdRenderExpr::Hold { body: values, .. } => values
            .last()
            .map(|value| value_expr_code(value, env))
            .unwrap_or_else(|| "GeneratedValue::Empty".to_owned()),
        boon_dd::DdRenderExpr::Call { callee, args } => call_value_code(callee, None, args, env),
        boon_dd::DdRenderExpr::Pipe { input, stage } => {
            let input = value_expr_code(input, env);
            stage_value_code(stage, Some(input), env)
        }
        boon_dd::DdRenderExpr::BinaryAdd { left, right } => format!(
            "GeneratedValue::Number(({}).number() + ({}).number())",
            value_expr_code(left, env),
            value_expr_code(right, env)
        ),
        boon_dd::DdRenderExpr::Match { arms, .. } => arms
            .iter()
            .find(|arm| arm.pattern != "__")
            .map(|arm| value_expr_code(&arm.value, env))
            .unwrap_or_else(|| "GeneratedValue::Empty".to_owned()),
    }
}

fn stage_value_code(
    stage: &boon_dd::DdRenderExpr,
    input: Option<String>,
    env: &BTreeMap<String, String>,
) -> String {
    match stage {
        boon_dd::DdRenderExpr::Call { callee, args } => call_value_code(callee, input, args, env),
        _ => value_expr_code(stage, env),
    }
}

fn call_value_code(
    callee: &str,
    input: Option<String>,
    args: &[boon_dd::DdRenderArg],
    env: &BTreeMap<String, String>,
) -> String {
    match callee {
        "Document/new" | "Scene/new" => input.unwrap_or_else(|| {
            named_arg_code(args, "root", env).unwrap_or_else(|| "GeneratedValue::Empty".to_owned())
        }),
        "Element/button" => {
            named_arg_code(args, "label", env).unwrap_or_else(|| "GeneratedValue::Empty".to_owned())
        }
        "Text/from_number" => input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned()),
        "Text/append" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            let suffix =
                first_arg_code(args, env).unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            format!(
                "GeneratedValue::Text(format!(\"{{}}{{}}\", ({}).text(), ({}).text()))",
                input, suffix
            )
        }
        "Text/join" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            let separator = named_arg_code(args, "separator", env)
                .unwrap_or_else(|| "GeneratedValue::Text(\",\".to_owned())".to_owned());
            format!(
                "match {} {{ GeneratedValue::List(values) => GeneratedValue::Text(values.into_iter().map(GeneratedValue::text).collect::<Vec<_>>().join(&({}).text())), other => GeneratedValue::Text(other.text()) }}",
                input, separator
            )
        }
        "Text/uppercase" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            format!("GeneratedValue::Text(({}).text().to_uppercase())", input)
        }
        "List/append" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            let item = named_arg_code(args, "item", env)
                .or_else(|| first_arg_code(args, env))
                .unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            format!(
                "match {} {{ GeneratedValue::List(mut values) => {{ values.push({}); GeneratedValue::List(values) }}, other => other }}",
                input, item
            )
        }
        "List/map" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            let Some(new_expr) = named_arg_expr(args, "new") else {
                return input;
            };
            let mut nested_env = env.clone();
            nested_env.insert("item".to_owned(), "item_value.clone()".to_owned());
            let mapped = value_expr_code(new_expr, &nested_env);
            format!(
                "match {} {{ GeneratedValue::List(values) => GeneratedValue::List(values.into_iter().map(|item_value| {}).collect()), other => other }}",
                input, mapped
            )
        }
        "List/retain" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            let predicate = named_arg_expr(args, "if")
                .map(|expr| {
                    let mut nested_env = env.clone();
                    nested_env.insert("item".to_owned(), "item_value.clone()".to_owned());
                    format!("({}).truthy()", value_expr_code(expr, &nested_env))
                })
                .unwrap_or_else(|| "true".to_owned());
            format!(
                "match {} {{ GeneratedValue::List(values) => GeneratedValue::List(values.into_iter().filter(|item_value| {{ let item_value = (*item_value).clone(); {} }}).collect()), other => other }}",
                input, predicate
            )
        }
        "List/count" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            if let Some(expr) = named_arg_expr(args, "if") {
                let mut nested_env = env.clone();
                nested_env.insert("item".to_owned(), "item_value.clone()".to_owned());
                let predicate = format!("({}).truthy()", value_expr_code(expr, &nested_env));
                format!(
                    "match {} {{ GeneratedValue::List(values) => GeneratedValue::Number(values.into_iter().filter(|item_value| {{ let item_value = (*item_value).clone(); {} }}).count() as i64), _ => GeneratedValue::Number(0) }}",
                    input, predicate
                )
            } else {
                format!(
                    "match {} {{ GeneratedValue::List(values) => GeneratedValue::Number(values.len() as i64), _ => GeneratedValue::Number(0) }}",
                    input
                )
            }
        }
        "Temperature/c_to_f" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            format!("GeneratedValue::Number(({}).number() * 9 / 5 + 32)", input)
        }
        "Bool/not" => {
            let input = input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned());
            format!(
                "GeneratedValue::Tag((if ({}).truthy() {{ \"False\" }} else {{ \"True\" }}).to_owned())",
                input
            )
        }
        _ => input.unwrap_or_else(|| "GeneratedValue::Empty".to_owned()),
    }
}

fn path_expr_code(path: &str, env: &BTreeMap<String, String>) -> String {
    let mut parts = path.split('.');
    let Some(root) = parts.next() else {
        return "GeneratedValue::Empty".to_owned();
    };
    let Some(mut code) = env.get(root).cloned() else {
        return "GeneratedValue::Empty".to_owned();
    };
    for part in parts {
        code = format!("({}).field({})", code, quote(part));
    }
    code
}

fn first_arg_code(args: &[boon_dd::DdRenderArg], env: &BTreeMap<String, String>) -> Option<String> {
    args.iter().find_map(|arg| match arg {
        boon_dd::DdRenderArg::Positional(value) => Some(value_expr_code(value, env)),
        boon_dd::DdRenderArg::Named { .. } => None,
    })
}

fn named_arg_code(
    args: &[boon_dd::DdRenderArg],
    name: &str,
    env: &BTreeMap<String, String>,
) -> Option<String> {
    named_arg_expr(args, name).map(|expr| value_expr_code(expr, env))
}

fn named_arg_expr<'a>(
    args: &'a [boon_dd::DdRenderArg],
    name: &str,
) -> Option<&'a boon_dd::DdRenderExpr> {
    args.iter().find_map(|arg| match arg {
        boon_dd::DdRenderArg::Named {
            name: arg_name,
            value,
        } if arg_name == name => Some(value),
        _ => None,
    })
}

fn quote(value: &str) -> String {
    format!("{value:?}")
}
