[initial]
expect_text = "0"

[[step]]
description = "increment"
actions = [
  { source = "store.sources.increment_button.event.press", value = [] }
]
expect_text = "1"
expect_monitor_changed = ["IncrementButtonEventPress", "Counter", "DocumentText"]

[[step]]
description = "persist and reload"
actions = [
  { command = "enable_persistence" },
  { source = "store.sources.increment_button.event.press", value = [] },
  { command = "reload" }
]
expect_text = "1"
