[initial]
expect_text = "saved"

[[step]]
description = "create record"
actions = [
  { source = "store.sources.save_button.event.press", value = [] }
]
expect_text = "saved"
expect_monitor_changed = ["DocumentOutput", "DocumentText"]
