[initial]
expect_text = "milk,bread"

[[step]]
description = "add shopping item"
actions = [
  { source = "new_item_input.text", value = "bread" },
  { source = "new_item_input.event.key_down.key", value = "Enter" }
]
expect_text = "milk,bread"
expect_monitor_changed = ["DocumentOutput", "DocumentText"]
