[initial]
expect_text = "a,b,c"

[[step]]
description = "map list through block"
actions = [
  { source = "list", value = ["a", "b", "c"] }
]
expect_text = "a,b,c"
expect_monitor_changed = ["ListMapBlock", "DocumentText"]
